"""
Django settings for consultorio project.

Generated by 'django-admin startproject' using Django 5.1.4.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Seguridad
SECRET_KEY = 'django-insecure-3%l!o9c_l^ji^1aw8%##dxv4ux!g6n1$-=rk4(bw@^o^lx1@-a'
DEBUG = False  # En producción, DEBUG debe estar siempre en False.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'blopa.duckdns.org']

# CSRF confiable para Ngrok y dominios de producción
CSRF_TRUSTED_ORIGINS = [
    'https://b7c0-131-100-185-93.ngrok-free.app',
    'https://tu-dominio.com',
]

# Apps instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'usuarios',
    'citas',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'consultorio.urls'

# Configuración de templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Ruta personalizada para templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'consultorio.wsgi.application'

# Base de datos
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'consultorio_db',  # Cambia al nombre exacto de la base en producción
        'USER': 'postgres',
        'PASSWORD': '922928aa',  # Contraseña de producción
        'HOST': 'localhost',  # Cambiar al host de tu base en producción si no es local
        'PORT': '5432',
    }
}

# Validación de contraseñas
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internacionalización
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True

# Archivos estáticos
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT =[ BASE_DIR / 'staticfiles']


# Para producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Redirecciones después del login/logout
LOGIN_URL = '/login/'  # Página de login
LOGIN_REDIRECT_URL = '/inicio/'  # Redirigir después del login
LOGOUT_REDIRECT_URL = '/'  # Redirigir después del logout

# Configuración por defecto para claves primarias
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
