# Generated by Django 5.1.4 on 2025-01-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_paciente_consulta_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='motivo_consulta',
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
